### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by sstidl** [aborroy/alf-tengine-ocr#1]
It's not really an Issue, but can you please refer me to some documentation where I can see how to use a share - rule to convert PDF to OCRed PDF?
I only found the REST call to make a rendition but no really useful way to integrate this.

My scenario is that every file which is uploaded to alfresco will automatically be OCRed and be full text searchable. Cant figure out how to do this...

any help is appreciated

regards 
stefan

**Comment by aborroy** [comment]
The code in this project can help you to add this feature:
https://github.com/keensoft/alfresco-simple-ocr

**Comment by sstidl** [comment]
Thank you for your answer!

I think I saw that, but it doesnt use the t-engine concept from alfresco 6+

i integrated alf-tengine-ocr with localtransform.ocr.url but dont understand how to use it with your code from https://github.com/keensoft/alfresco-simple-ocr

will the code from https://github.com/keensoft/alfresco-simple-ocr still work with dockerized alfresco 6.x stack? 

thanks for your time and stay healthy,
Stefan

**Comment by aborroy** [comment]
You can see Alfresco Simple OCR in action with a Dockerized Alfresco using https://github.com/Alfresco/alfresco-docker-installer

The code from https://github.com/keensoft/alfresco-simple-ocr includes a behaviour for the repository. You could port this part to this project in order to get the OCR done every time a new PDF is uploaded.

**Comment by krutik-jayswal** [comment]
@aborroy : Do you mean we need to copy code from this project in to https://github.com/keensoft/alfresco-simple-ocr ?
Actually I am struggling with multiple pdf file uploads.So I am trying to make batch management solution using api for OCR?any suggestion for this?

**Comment by aborroy** [comment]
This project is the Transformer part. If you want to create an Action in order to run this Transformer, then you need some code from  https://github.com/keensoft/alfresco-simple-ocr, despite you can fire the transformation action by using some other configuration.

**Comment by dgradecak** [comment]
@aborroy I guess with the "targetMediaType": "alfresco-metadata-embed"  and the "embed-metadata" action you can close this issue

**Comment by aborroy** [comment]
Right!
