### ISSUE TITLE
The OCR action is not coming in the dropdown box when configuring the rule in Alfresco share

### ISSUE THREAD

**Issue by atultalhar** [aborroy/alf-tengine-ocr#10]
I have configured the Tengine-ocr as you mentioned in the document with this code. but still I am not sure somehow it is not coming in dropdown box when we are trying to configure in Alfresco share.
Did you faced this issue. ?

**Comment by aborroy** [comment]
Deploy the `embed-metadata-action-1.0.0.jar` in Alfresco Repository.

https://github.com/aborroy/alf-tengine-ocr#deployment-with-acs-stack
