### ISSUE TITLE
Error response from daemon: pull access denied

### ISSUE THREAD

**Issue by guilhermepolicarpo** [aborroy/alf-tengine-ocr#11]
![image](https://user-images.githubusercontent.com/13804537/215931957-52a3af5a-b593-4571-92ca-706f4d2cde26.png)
I'm getting this error. How can I solve?

tks

**Comment by douglascrp** [comment]
Hello.

Have you followed the steps described at https://github.com/aborroy/alf-tengine-ocr#build-docker-image-for-alfresco-ocr-transformer before using it?
