### ISSUE TITLE
Creates no new document version on higher execution time

### ISSUE THREAD

**Issue by Jack12816** [aborroy/alf-tengine-ocr#12]
Hey @aborroy - first off: thanks for the OCR transformer, it looks nice and lean!

I'm struggling with a migration from a hand-rolled OCR pipeline with Alfresco 5.0 (CE) to your OCR transformer with Alfresco 7.4 (CE). The direct integration as a folder rule would be much simpler. My setup works so far that I can upload the [quick.pdf](https://github.com/aborroy/alf-tengine-ocr/blob/master/ats-transformer-ocr/src/main/resources/quick.pdf) from this repo and the OCR magic (new document version) works as expected. That's great! 

Here's my problem: When I upload a real PDF file (426kb, one page, PDF version 1.4) then no new document version is created, never. My guess is that the issue is caused by resource limits. I've experimented with file size and I think it's more related to the execution time. A bigger file (508kb, one page, PDF version 1.4) sometimes succeeds in a new document version, but not always. I'm pretty sure it's not the file size as the OCR transformer [does not configure](https://github.com/aborroy/alf-tengine-ocr/blob/1b707df4e604c78be0eb2cb86cad046d4ef07e21/ats-transformer-ocr/src/main/resources/engine_config.json) the `maxSourceSizeBytes` - which defaults to `-1` (no limit) [according to the docs](https://docs.alfresco.com/transform-service/latest/config/#default-maxsourcesizebytes-and-priority-values).

Here are some screenshots:
* [OCR transformer log](https://s3-eu-west-1.amazonaws.com/jack12816/public/images/img-2023-06-27-190818.png)
* [Alfresco Content App](https://s3-eu-west-1.amazonaws.com/jack12816/public/images/img-2023-06-27-190914.png)

I searched for [transformer timeouts](https://docs.alfresco.com/transformation-engine/2.2/config/#transformation-timeout-considerations) and configured on the repository the following settings:

```
-Dtransformer.timeout.default=300
-Dtransformserver.transformationTimeout=300
-Dcontent.transformer.default.timeoutMs=300000    
```

but this does not change the situation. Unfortunately, I was not able to figure out where [the `transformOptions.get(TIMEOUT)`](https://github.com/aborroy/alf-tengine-ocr/blob/1b707df4e604c78be0eb2cb86cad046d4ef07e21/ats-transformer-ocr/src/main/java/org/alfresco/transformer/executors/OcrmypdfCommandExecutor.java#L94) comes from or how to set it properly.

While digging into this I recognized, when the execution time is less than 5 seconds the new document version is created. I didn't found any defaults for the `transformOptions` regarding the timeout.

Maybe you could give me a hint? :)

**Comment by Jack12816** [comment]
Looks like I found something [on the repository.properties](https://github.com/Alfresco/alfresco-community-repo/blob/fb235e168247c2f950cb04d336f74e9a89da0ed4/repository/src/main/resources/alfresco/repository.properties#L757-L759)! 

```
httpclient.config.transform.socketTimeout=5000
httpclient.config.transform.connectionRequestTimeout=5000
httpclient.config.transform.connectionTimeout=5000
```

When I set these configs higher it works as expected. So nevermind! :v:

**Comment by Jack12816** [comment]
Maybe this is useful to someone else who runs into this issue.

**Comment by aborroy** [comment]
Thanks @Jack12816
