### ISSUE TITLE
amd64 image for 1.0.0-deu-fra-spa-ita not available in dockerhub

### ISSUE THREAD

**Issue by JanUlrichR** [aborroy/alf-tengine-ocr#15]
Hey,

we noticed that the tag 1.0.0-deu-fra-spa-ita does not support the amd64 architecture. The tag 1.0.0 does support it.
Was there an error when deploying the latest changes?

**Comment by aborroy** [comment]
Multi-language Docker Image is available now in both architectures:
https://hub.docker.com/layers/angelborroy/alfresco-tengine-ocr/1.0.0-deu-fra-spa-ita/images/sha256-467d20a0bb5b2cd4648150dd6aab406586c4ee49d7b4be5ec7b3b032cee876c7?context=repo
