### ISSUE TITLE
Maven build error due to "SNAPSHOT" reference

### ISSUE THREAD

**Issue by misterteetee** [aborroy/alf-tengine-ocr#7]
Line 18 references "-SNAPSHOT" which doesn't appear to be valid as of today (my luck!). Removing that and going for "2.5.4" appears to work for me. (my first submitted issue - be gentle)

https://github.com/aborroy/alf-tengine-ocr/blob/5f1c81cfe2c52bb3d5153896033f1df7b0573b68/ats-transformer-ocr/pom.xml#L18

**Comment by aborroy** [comment]
Thanks for the feedback. Updated now!
