### ISSUE TITLE
Migrate from previous 6.2 with simple-ocr

### ISSUE THREAD

**Issue by lonestaritaly** [aborroy/alf-tengine-ocr#8]
I know this is probably not the best way to ask this question, but I can't find another place where to ask.

What would be the procedure (if possible) for migrating/upgrading from Alfresco 6.2 with simple-ocr (docker) to Alfresco 7.1 with TransformEngine OCR (docker) ?

I've successfully done a backup of my data from 6.2, restored it to 7.1 installation and almost everything works as expected.
But in some cases, for instance when trying to access User folder from ACA, there is an error that I've tracked down to : 

{"error":{"errorKey":"framework.exception.ApiDefault","statusCode":500,"briefSummary":"A namespace prefix is not registered for uri http://www.keensoft.es/model/content/ocr/1.0","stackTrace":"Per motivi di sicurezza l'analisi dello stack non viene più visualizzata, ma viene mantenuta la proprietà per le versioni precedenti","descriptionURL":"https://api-explorer.alfresco.com","logId":"ae148681-aa5b-4cf3-b33d-a46201617545"}}

I guess my documents have reference to the namespace of the previous module, and it is not found.

What should be done to fix the situation?

**Comment by aborroy** [comment]
The previous add-on (available in https://github.com/keensoft/alfresco-simple-ocr) was using a custom content model when OCRing a PDF document:
https://github.com/keensoft/alfresco-simple-ocr/blob/master/simple-ocr-repo/src/main/resources/alfresco/module/simple-ocr-repo/model/ocr-model.xml

If you want to upgrade to this project from that one, you'll need to deploy this custom content model in Alfresco Repository.

**Comment by lonestaritaly** [comment]
Thanks a lot! I imported the model and now I don't see those errors anymore.
